import Link from "next/link";
import { Logo } from "@/components/logo";

export default function TermsPage() {
  return (
    <div className="min-h-screen flex flex-col">
      <header className="border-b bg-background">
        <div className="max-w-3xl mx-auto px-6 h-16 flex items-center justify-between">
          <Logo size={28} href="/" />
          <Link href="/" className="text-sm text-muted-foreground hover:text-foreground transition-colors">← Home</Link>
        </div>
      </header>

      <main className="flex-1 max-w-3xl mx-auto px-6 py-12">
        <h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
        <p className="text-muted-foreground text-sm mb-10">Last updated: March 28, 2026</p>

        <div className="prose prose-base max-w-none text-foreground leading-7
          prose-headings:text-foreground prose-headings:font-bold
          prose-h2:text-xl prose-h2:mt-10 prose-h2:mb-3
          prose-p:text-muted-foreground prose-li:text-muted-foreground">

          <p>
            Welcome to CounterPro. By accessing or using counterproai.com, you agree to these Terms of Service. Please read them carefully.
          </p>

          <h2>What CounterPro Is</h2>
          <p>
            CounterPro is an AI-powered negotiation coaching tool. It provides strategy, scripts, and analysis to help you negotiate real estate transactions more effectively.
          </p>
          <p>
            <strong>CounterPro is not a licensed real estate broker, agent, attorney, or financial advisor.</strong> The content generated by CounterPro is for informational and coaching purposes only and does not constitute legal, financial, or professional real estate advice. You are solely responsible for any decisions you make based on CounterPro&rsquo;s output.
          </p>

          <h2>Eligibility</h2>
          <p>
            You must be at least 18 years old to use CounterPro. By using the service you represent that you meet this requirement.
          </p>

          <h2>Account</h2>
          <p>
            You are responsible for maintaining the security of your account credentials. Notify us immediately at <a href="mailto:support@counterproai.com" className="underline">support@counterproai.com</a> if you suspect unauthorized access. We are not liable for losses caused by unauthorized use of your account.
          </p>

          <h2>Payments and Subscriptions</h2>
          <ul>
            <li><strong>Single deal — $50</strong>: A one-time payment that grants one negotiation package generation.</li>
            <li><strong>Monthly subscription — $100/month</strong>: Grants unlimited negotiation packages for the duration of your active subscription. Billed monthly and automatically renews until cancelled.</li>
          </ul>
          <p>
            All payments are processed by Stripe. Prices are in USD and do not include applicable taxes. We reserve the right to change pricing with reasonable notice.
          </p>

          <h2>Cancellation and Refunds</h2>
          <p>
            You may cancel your subscription at any time. Cancellation takes effect at the end of the current billing period — you retain access through that date. We do not offer refunds on single-deal purchases once the package has been generated. If you have not yet generated a package and believe a refund is warranted, contact us at <a href="mailto:support@counterproai.com" className="underline">support@counterproai.com</a> within 24 hours of purchase.
          </p>

          <h2>Acceptable Use</h2>
          <p>You agree not to:</p>
          <ul>
            <li>Use CounterPro for any unlawful purpose or in violation of any applicable laws.</li>
            <li>Attempt to reverse-engineer, copy, or resell the service or its AI-generated outputs commercially without permission.</li>
            <li>Input false, fraudulent, or misleading information with intent to harm another party.</li>
            <li>Abuse the service in a way that places unreasonable load on our infrastructure.</li>
          </ul>

          <h2>AI-Generated Content</h2>
          <p>
            CounterPro&rsquo;s negotiation packages are generated by AI and are based solely on the information you provide. Outputs may contain errors, omissions, or advice that is not appropriate for your specific situation. Always verify important figures (comparable sales, market data, legal requirements) with qualified professionals before acting.
          </p>
          <p>
            AI outputs are not guaranteed to be accurate, complete, or current. Market conditions change rapidly and the information provided may not reflect real-time data.
          </p>

          <h2>Intellectual Property</h2>
          <p>
            The CounterPro platform, branding, and code are owned by CounterPro. Negotiation packages generated for you belong to you for your personal use. You may not resell or redistribute AI-generated packages as your own product or service.
          </p>

          <h2>Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by law, CounterPro and its operators shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the service, including any losses resulting from reliance on AI-generated negotiation advice. Our total liability to you shall not exceed the amount you paid us in the 3 months prior to the claim.
          </p>

          <h2>Disclaimer of Warranties</h2>
          <p>
            CounterPro is provided &ldquo;as is&rdquo; without warranties of any kind, express or implied. We do not warrant that the service will be uninterrupted, error-free, or that results will meet your expectations.
          </p>

          <h2>Changes to These Terms</h2>
          <p>
            We may update these Terms from time to time. Continued use of CounterPro after changes are posted constitutes your acceptance. We will notify you of material changes via email.
          </p>

          <h2>Governing Law</h2>
          <p>
            These Terms are governed by the laws of the State of Indiana, without regard to conflict of law principles.
          </p>

          <h2>Contact</h2>
          <p>
            Questions about these Terms? Email us at <a href="mailto:support@counterproai.com" className="underline">support@counterproai.com</a>.
          </p>
        </div>
      </main>

      <footer className="border-t py-6 px-6 text-center text-xs text-muted-foreground">
        <div className="flex justify-center gap-6">
          <Link href="/privacy" className="hover:text-foreground underline underline-offset-2">Privacy</Link>
          <Link href="/terms" className="hover:text-foreground underline underline-offset-2">Terms</Link>
          <a href="mailto:support@counterproai.com" className="hover:text-foreground underline underline-offset-2">Support</a>
        </div>
      </footer>
    </div>
  );
}
